apiVersion: v1 
kind: Service 
metadata: 
  name: shire-service 
spec: 
  selector: 
    app: shire-app 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8080 
    type: LoadBalancer
    externalTrafficPolicy: Local
