# nonk8s
# kind-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: workshop
networking:
  # Configure custom CNI (for Cilium)
  disableDefaultCNI: true
  # Configure pod subnet for Cilium
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            authentication-token-webhook: "true"
            authorization-mode: "Webhook"
      - |
        kind: KubeletConfiguration
        kubeletConfig:
          serverTLSBootstrap: true
          authentication:
            webhook:
              enabled: true
          authorization:
            mode: Webhook
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker

# Configure containerd to use overlay2 storage driver
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true